version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
    timezone: America/Halifax
  open-pull-requests-limit: 2
  ignore:
  - dependency-name: github.com/golangci/golangci-lint
    versions:
    - 1.36.0
    - 1.37.0
    - 1.37.1
    - 1.38.0
