run:
  deadline: 5m

  # which dirs to skip: they won't be analyzed;
  # can use regexp here: generated.*, regexp is applied on full path;
  # default value is empty list, but next dirs are always skipped independently
  # from this option's value:
  #   	vendor$, third_party$, testdata$, examples$, Godeps$, builtin$
  skip-dirs:
    - generated/.*

  skip-files:
    - .*generated.*

issues:
  # Disable maximums so we see all issues
  max-per-linter: 0
  max-same-issues: 0

  # golangci-lint ignores missing docstrings by default. That's no good!
  exclude-use-default: false

linters-settings:
 goimports:
    # put imports beginning with prefix after 3rd-party packages;
    # it's a comma-separated list of prefixes
    local-prefixes: github.com/manifoldco/marketplace

linters:
  disable-all: true
